### ISSUE TITLE
persist requester protocol

### ISSUE THREAD

**Issue by lanefu** [armbian/dl-router#2]
currently all redirects goto https..... should persist HTTP if requester used http

**Comment by yaleman** [comment]
Could be worth checking the nginx logs, I can't reproduce the issue with the local docker test config... I created a PR for a bunch of tests and things that might help with maintenance https://github.com/armbian/dl-router/pull/11

**Comment by lanefu** [comment]
[AR-604]

[AR-604]: https://armbian.atlassian.net/browse/AR-604

**Comment by MichaIng** [comment]
PR up: #14
