### ISSUE TITLE
stpete-mirror.armbian.com mirror down

### ISSUE THREAD

**Issue by MichaIng** [armbian/dl-router#21]
Hey guys. I guess this is not the right place to report it, but couldn't find a matching sub forum as well: The `stpete-mirror.armbian.com` is currently not reachable which makes every second `apt update` or package download fail here. Please guide me if there is a better place to report issues with mirrors.

**Comment by igorpecovnik** [comment]
Hey!

We see here https://github.com/armbian/mirror if something is wrong, but it takes some time / hours to notice. This detection and disabling / enabling of mirrors could be improved and automatised some day. 

We were doing something on this mirror today, but during my quick / before bed inspection / I couldn't find what the problem is so I have disabled it.

Thanks for prompt report.

**Comment by igorpecovnik** [comment]
Issue tracker on https://github.com/armbian/mirror has been enabled.

**Comment by MichaIng** [comment]
Ah thanks for the info, so I'll have a look there next time and in case report there. If I find time during the weekend, I'll open a PR for a scheduled mirror check, looping though `http://redirect.armbian.com/mirrors` an `http://apt.armbian.com/mirrors` via [lychee](https://github.com/lycheeverse/lychee) to check whether all mirrors are online, probably with a batch for users which do not get failed workflow notifications 🙂.

**Comment by igorpecovnik** [comment]
https://github.com/armbian/mirror#mirrors-error-count

We have some [primitive parallel periodic link checking](https://github.com/armbian/mirror/blob/master/.github/workflows/rootfs-sync.yml#L85-L90) within Github Actions which provides some information about the mirror status. Idea from here is to set some threshold, after which additional trigger is set - removing / enabling a mirror. That part was not done yet - just an idea.

**Comment by MichaIng** [comment]
Ah I see. Currently it just counts up, right? Basically a status for each mirror would be great for users to be more certain whether it's a server or client/network issue. I'm always checking from home and a remove VPS to know better.

Automatic mirror disabling/enabling would be great indeed. Probably an URL checker (or the custom parallel loop) could repeat checking failed mirrors a few times to rule out a short temporary issue and then use the result as status and/or reason to disable the mirror, likewise assure that all mirrors which passed the URL check are (re-)enabled.

But I see I first need to better understand what and how the existing workflows do already.
