### ISSUE TITLE
Is this for Armbian mirrors?

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [armbian/dl-router#7]
I am looking around trying to find if there is a way I can get a US based mirror of apt.armbian.com in service. From what I've gathered of documentation and forums, I believe http://apt.armbian.com is the sole mirror. Is this dl-router tool designed to act the way the Debian repo URL works, where it more or less acts as an IP sprayer (load balancer) redirecting requests based on geolocation?

**Comment by lanefu** [comment]
Yep sorry I didn't see your issue earlier
